#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ "$#" == 0 ]]; then
    set -- default
  fi

  shift
  exec gotty -w --once -a 127.0.0.1 -p 31337 docker run -ti ubuntu:xenial
}

main "$@"

