#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_gotty="$(gotty -v 2>/dev/null | awk '{print $3}' || true)"
  jq -n --arg gotty "$ver_gotty" '{gotty: $gotty}'
}

version "$@"
